// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yichen.yao.netty.grpc.example.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   * @return The realname.
   */
  String getRealname();
  /**
   * <code>string realname = 1;</code>
   * @return The bytes for realname.
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
