// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yichen.yao.netty.grpc.example.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
