// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yichen.yao.netty.grpc.example.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   * @return The requestInfo.
   */
  String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   * @return The bytes for requestInfo.
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
