// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yichen.yao.netty.grpc.example.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .yichen.yao.netty.grpc.example.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .yichen.yao.netty.grpc.example.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .yichen.yao.netty.grpc.example.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .yichen.yao.netty.grpc.example.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .yichen.yao.netty.grpc.example.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
