// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yichen_yao_netty_grpc_example_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yichen_yao_netty_grpc_example_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\035yichen.yao.netty.grp" +
      "c.example\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t" +
      "\"\036\n\nMyResponse\022\020\n\010realname\030\001 \001(\t\"\035\n\016Stud" +
      "entRequest\022\013\n\003age\030\001 \001(\005\":\n\017StudentRespon" +
      "se\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 " +
      "\001(\t\"^\n\023StudentResponseList\022G\n\017studentRes" +
      "ponse\030\001 \003(\0132..yichen.yao.netty.grpc.exam" +
      "ple.StudentResponse\"%\n\rStreamRequest\022\024\n\014" +
      "request_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\r" +
      "response_info\030\001 \001(\t2\352\003\n\016StudentService\022n" +
      "\n\025GetRealNameByUsername\022(.yichen.yao.net" +
      "ty.grpc.example.MyRequest\032).yichen.yao.n" +
      "etty.grpc.example.MyResponse\"\000\022u\n\020GetStu" +
      "dentsByAge\022-.yichen.yao.netty.grpc.examp" +
      "le.StudentRequest\032..yichen.yao.netty.grp" +
      "c.example.StudentResponse\"\0000\001\022\203\001\n\030GetStu" +
      "dentsWrapperByAges\022-.yichen.yao.netty.gr" +
      "pc.example.StudentRequest\0322.yichen.yao.n" +
      "etty.grpc.example.StudentResponseList\"\000(" +
      "\0010\001\022k\n\006BiTalk\022,.yichen.yao.netty.grpc.ex" +
      "ample.StreamRequest\032-.yichen.yao.netty.g" +
      "rpc.example.StreamResponse\"\000(\0010\001B/\n\035yich" +
      "en.yao.netty.grpc.exampleB\014StudentProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yichen_yao_netty_grpc_example_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yichen_yao_netty_grpc_example_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_yichen_yao_netty_grpc_example_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yichen_yao_netty_grpc_example_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_yichen_yao_netty_grpc_example_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_yichen_yao_netty_grpc_example_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_yichen_yao_netty_grpc_example_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_yichen_yao_netty_grpc_example_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_yichen_yao_netty_grpc_example_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_yichen_yao_netty_grpc_example_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_yichen_yao_netty_grpc_example_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_yichen_yao_netty_grpc_example_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_StreamRequest_descriptor,
        new String[] { "RequestInfo", });
    internal_static_yichen_yao_netty_grpc_example_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_yichen_yao_netty_grpc_example_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yichen_yao_netty_grpc_example_StreamResponse_descriptor,
        new String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
