// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package yichen.yao.netty.grpc.example;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yichen.yao.netty.grpc.example.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();
}
